custom.schedule.keyword.run: true
spring.jwt.secret: spring2redish1u2n3j4w5t6k7e8y901

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: h2
  redis:    host: localhost
    password: hunredis
    port: 6379

api:
  kakaosearch:
    host: https://dapi.kakao.com
    uri:
      keyword: /v2/local/search/keyword.json
    token: 3ec2ecad3c005f756b06ad32d13ddd01
    authHeader: KakaoAK
    
# logging
logging.level:
  me.step4: debug
  org.springframework.web: debug
  org.hibernate.sql: info
  jpa: info
        